FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --legacy-peer-deps

# Copia o restante do código
COPY . .

# Expõe a porta do servidor de desenvolvimento Next.js
EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# Roda o servidor de desenvolvimento
CMD ["npm", "run", "dev"]
